---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-dev
  labels:
    app: postgres-dev
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pg-pv-dev-pv-volume
  labels:
    type: local
    app: postgres-dev
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-pv-dev-claim
  labels:
    app: postgres-dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-dev
  template:
    metadata:
      labels:
        app: postgres-dev
    spec:
      containers:
        - name: postgres-dev
          image: postgres:14.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config-dev
          volumeMounts:
            - mountPath: /var/lib/postgresql/db-files
              name: postgredb-dev
      volumes:
        - name: postgredb-dev
          persistentVolumeClaim:
            claimName: pg-pv-dev-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-dev
  labels:
    app: postgres-dev
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres-dev